replicaCount: 1

image:
  repository: ghcr.io/kosmos-education/namespace-protection
  pullPolicy: Always
  tag: v1.0.1

webhook:
  rejectionMessage: "This namespace is protected against deletion"
  annotationName: "kosmos-education.io/protected"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
